---

# This is meant to be run after the vmware_gather_facts playbook to discover the VM Guest IP address
- name: OS Hardening
  hosts: '{{ vm_ip_address }}'
  gather_facts: true

  roles:
    - dev-sec.os-hardening