---
- name: VMWare Deploy CentOS OVA
  hosts: all

  tasks:

     - name: Download OVA from ESXi Datastore
       get_url: 
          url: '{{ esxi_ova_path }}'
          dest: /tmp/'{{ local_ova_path }}'
          mode: '0440'

     - name: Deploy OVA to ESXi 
       vmware_deploy_ovf:
          hostname: '{{ esxi_hostname }}'
          username: '{{ esxi_username }}'
          password: '{{ esxi_password }}'
          datastore: '{{ esxi_datastore }}'
          name: '{{ esxi_new_vm_name }}'
          networks: "{u'VM Network':u'{{ ProvisioningNetworkLabel }}'}"
          validate_certs: no
          power_on: yes
          disk_provisioning: thin
          ovf: /tmp/'{{ local_ova_path }}'
       delegate_to: localhost

     - name: Delete OVA file
       file:
         path: /tmp/'{{ local_ova_path }}'
         state: absent



     
      


