---
- name: VMWare Deploy CentOS OVA
  hosts: all
  gather_facts: false

  tasks:

     - name: Download OVA from ESXi Datastore
       get_url: 
          url: '{{ esxi_ova_path }}'
          dest: ./'{{ local_ova_path }}'
          mode: '0440'
          validate_certs: false
          url_username: '{{ esxi_username }}'
          url_password: '{{ esxi_password }}'
       delegate_to: localhost

     - name: Deploy OVA to ESXi 
       vmware_deploy_ovf:
          hostname: '{{ esxi_hostname }}'
          username: '{{ esxi_username }}'
          password: '{{ esxi_password }}'
          datastore: '{{ esxi_datastore }}'
          name: '{{ esxi_new_vm_name }}'
          networks: "{{ esxi_vmnetwork}}'{{ esxi_vm_provision_network }}"
          validate_certs: no
          power_on: yes
          disk_provisioning: thin
          ovf: ./'{{ local_ova_path }}'
       delegate_to: localhost


     - name: Gather facts from standalone ESXi server having datacenter as 'ha-datacenter'
       vmware_guest_facts:
          hostname: '{{ esxi_hostname }}'
          username: '{{ esxi_username }}'
          password: '{{ esxi_password }}'
          datacenter: ha-datacenter
          validate_certs: no
          name: '{{ esxi_new_vm_name }}'
       delegate_to: localhost
       register: esxi_vm_guest_facts

     - name: Delete OVA file
       file:
         path: /tmp/'{{ local_ova_path }}'
         state: absent
       delegate_to: localhost



     
      


