---
# tasks file for add_tower_host
- name: Add tower host role
  tower_host:
    name: '{{ vm_ip_address }}'
    inventory: "VMWare Guest VMs"
    state: present
    tower_username: '{{ tower_username }}'
    tower_password: '{{ tower_password }}'
    validate_certs: no

   